# Site settings
title: "net magazine | money survey"
email: "cole@ournameismud.co.uk"
baseurl: "/net-survey" # the subpath of your site, e.g. /blog/
twitter_username: "@cole007"
github_username:  "cole007"

# Build settings
markdown: redcarpet
pygments: true